ci: fix emulator clean

diff --git a/.github/workflows/test-mobile-e2e-reusable.yml b/.github/workflows/test-mobile-e2e-reusable.yml
--- a/.github/workflows/test-mobile-e2e-reusable.yml
+++ b/.github/workflows/test-mobile-e2e-reusable.yml
@@ -185,8 +185,9 @@ jobs:
         shell: bash
 
       - name: Create iOS simulator
-        id: simulator
-        run: xcrun simctl create "iOS Simulator" "iPhone 15"
+        run: |
+          xcrun simctl list devices | grep 'iOS Simulator' | awk -F '[()]' '{print $2}' | xargs -I {} sh -c 'echo "Deleting simulator: {}"; xcrun simctl delete {} || echo "Failed to delete: {}"'
+          xcrun simctl create "iOS Simulator" "iPhone 15"
 
       - name: Build iOS app for Detox test run
         if: steps.detox-build.outputs.cache-hit != 'true' || inputs.production_firebase == 'true'
@@ -234,7 +235,7 @@ jobs:
           disable_cache: ${{ inputs.disable-turbo-cache || false }}
 
       - name: Delete iOS simulator
-        if: ${{ always() }}
+        if: ${{ always() || cancelled() }}
         run: |
           xcrun simctl list devices | grep 'iOS Simulator' | awk -F '[()]' '{print $2}' | xargs -I {} sh -c 'echo "Deleting simulator: {}"; xcrun simctl delete {} || echo "Failed to delete: {}"'
 
