ci: fix emulator clean

diff --git a/.github/workflows/test-mobile-e2e-reusable.yml b/.github/workflows/test-mobile-e2e-reusable.yml
--- a/.github/workflows/test-mobile-e2e-reusable.yml
+++ b/.github/workflows/test-mobile-e2e-reusable.yml
@@ -178,8 +178,9 @@ jobs:
           pnpm build:dummy-apps
         shell: bash
       - name: Create iOS simulator
-        id: simulator
-        run: xcrun simctl create "iOS Simulator" "iPhone 15"
+        run: |
+          xcrun simctl list devices | grep 'iOS Simulator' | awk -F '[()]' '{print $2}' | xargs -I {} sh -c 'echo "Deleting simulator: {}"; xcrun simctl delete {} || echo "Failed to delete: {}"'
+          xcrun simctl create "iOS Simulator" "iPhone 15"
       - name: Build iOS app for Detox test run
         if: steps.detox-build.outputs.cache-hit != 'true' || inputs.production_firebase == 'true'
         run: pnpm mobile e2e:ci -p ios -b $([[ "$PRODUCTION" == "true" ]] && printf %s '--production')
@@ -205,7 +206,7 @@ jobs:
           SEED: ${{ secrets.SEED_QAA_B2C }}
           INPUT_SPECULOS: ${{ env.SPECULOS_RUN }}
       - name: Delete iOS simulator
-        if: ${{ always() }}
+        if: ${{ always() || cancelled() }}
         run: |
           xcrun simctl list devices | grep 'iOS Simulator' | awk -F '[()]' '{print $2}' | xargs -I {} sh -c 'echo "Deleting simulator: {}"; xcrun simctl delete {} || echo "Failed to delete: {}"'
       - name: Upload test artifacts
